import './previewCard.css';

import SkeletonText from '../Skeleton/SkeletonText';
import SkeletonImg from '../Skeleton/SkeletonImg';

import imgNotFound from '../../images/img_not_found.jpg';

const PreviewCard = ({screen, loading}) => {
    return (
        <div className="report__data--wrapper report__preview">
            <div className="report__data--container">
                <p className='report__preview--title'>Website preview</p>
                {
                    !loading ? 
                    <div className="report__review--img">
                        <img src={screen ? screen : imgNotFound} alt="website screenshot" /> 
                    </div> : 
                    <SkeletonImg/>
                }
                <div className="report__preview--aditional-info">
                    {
                    loading ? 
                    <SkeletonText/> : 
                    <p>Here the last preview generated by <span>Page Speed Insights of Google</span></p>
                    }
                </div>
            </div>
        </div>
    );
}
 
export default PreviewCard;