
import './reportDataCards.css';
import CircularProgressBar from '../ProgressBar/CircularProgressBar';
import RadarChartComponent from '../RadarChart/RadarChart';
import SkeletonComponent from '../Skeleton/Skeleton';

import imgNotFound from '../../images/img_not_found.jpg';

const ReportDataCards = ({pageData, loading}) => {

    const isEmpty = (obj) => {
        return Object.entries(obj).length === 0;
    };
    
    const {FCP, SI, LCP, TBT, CLS, screen} = pageData;
    let CLS_percentage = null
    let FCP_percentage = null
    let SI_percentage = null
    let LCP_percentage = null
    let TBT_percentage = null
    let score = null
        
    if (pageData) {
        CLS_percentage = (1-(CLS / 0.82)) * 0.25;
        FCP_percentage = (1-(FCP / 4000)) * 0.10;
        SI_percentage = (1-(SI / 5000)) * 0.10;
        LCP_percentage = (1-(LCP / 6000)) * 0.25;
        TBT_percentage = (1-(TBT / 2000)) * 0.30;
        score = Math.round((CLS_percentage + FCP_percentage + SI_percentage + LCP_percentage + TBT_percentage) * 100);
    }


    let seoScoreMsg = isEmpty(pageData) ? "Not data..." : `The speed of your page is ${score}% of optimal.`
    
    seoScoreMsg = loading ? "Loading..." : seoScoreMsg
    
    return ( 
        <div className="report__data--content">
            <div className="report__data--wrapper report--seo-score">
                <div className="report__data--container">
                    <div className="report--seo-score--title">SEO score</div>
                    
                    <CircularProgressBar 
                    percentage={pageData && pageData.score ? score : 0}
                    className="report--seo-progress-bar" /> 

                    <div className="report__seo--percentage-info">
                        <div className="indicator red__indicator">0-25</div>
                        <div className="indicator orange__indicator">26-50</div>
                        <div className="indicator yellow__indicator">51-75</div>
                        <div className="indicator green__indicator">75-100</div>
                    </div>
                
                    
                    <div className="report--seo-score--desc">{seoScoreMsg}</div>
                </div>
            </div>

            <div className="report__data--wrapper report--preview">
                <div className="report__data--container">
                    <p className='report__data--title'>Website preview</p>
                    {!loading ? 
                    <div className="report__review--img">
                        <img src={pageData && pageData.screen ? screen : imgNotFound} alt="website screenshot" /> 
                    </div>
                    : <SkeletonComponent/>}
                    <p className="report__data--aditional-info">
                    Here the last preview generated by <span>Page Speed Insights of Google</span>
                    </p>
                </div>
            </div>

            <div className="report__data--wrapper report--analysis">
                <div className="report__data--container report__analysis--radar">
                    <p className='report__analysis--title'>
                    SEO Categories Analysis
                    </p>
                    <RadarChartComponent pageData={pageData}/>
                </div>
            </div>
        </div>      
    );
}
 
export default ReportDataCards;